version: 2
jobs:
  build:
    docker:
      - image: pecorarista/conda-nlp-japanese
      - image: postgres:9.6
        environment:
          POSTGRES_USER: nlp
          POSTGRES_DB: test_db
    steps:
      - checkout
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - restore_cache:
          keys:
            - python-project-template-{{ checksum "environment-fixed.yaml" }}
      - run:
          name: Create an environment
          command: |
            if [ ! -d /opt/nlp/.conda/envs/circleci ]
            then
                conda env create -f environment-fixed.yaml -n circleci --quiet
            fi
      - save_cache:
          key: python-project-template-{{ checksum "environment-fixed.yaml" }}
          paths:
            - /opt/nlp/.conda
      - run:
          name: Create `config.toml`
          command: |
            cat example.toml \
              | sed -e "s#^uri = 'postgresql://ubuntu@localhost:5432/DB'\$#uri = 'postgresql://nlp@localhost:5432/test_db'#" \
              | tee config.toml
      - run:
          name: Check formats
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate circleci
            flake8 mypkg
            flake8 tests
            isort --recursive --check-only mypkg
            isort --recursive --check-only tests
      - run:
          name: Run unit tests
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate circleci
            # pytest --run-slow
            pytest
