version: 2
jobs:
  build:
    docker:
      - image: kennethreitz/pipenv
        user: circleci
    steps:
      - checkout
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - run:
          name: Create `.env`
          command: echo "WORKON_HOME=/home/circleci/pipenv\n" > .env
      - restore_cache:
          keys:
            - python-project-template-{{ checksum "Pipfile.lock" }}
      - run:
          name: Create an environment
          command: pipenv install
      - save_cache:
          key: python-project-template-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/pipenv
      - run:
          name: Check formats
          command: |
            source /home/circleci/pipenv/bin/activate
            flake8 mypkg
            flake8 tests
            isort --recursive --check-only mypkg
            isort --recursive --check-only tests
      - run:
          name: Run unit tests
          command: |
            source /home/circleci/pipenv/bin/activate
            pytest
