version: 2
jobs:
  build:
    docker:
      - image: pecorarista/pipenv
        user: circleci
    steps:
      - checkout
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - run:
          name: Export environment variables
          command: echo -e 'PIPENV_VENV_IN_PROJECT=1\n' > .env
      - run:
          name: Create `config.toml`
          command: cp example.toml config.toml
      - restore_cache:
          keys:
            - python-project-template-{{ checksum "Pipfile.lock" }}
      - run:
          name: Create an environment
          command: pipenv install
      - save_cache:
          key: python-project-template-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/project/.venv
            - /home/circleci/.cache/pipenv
      - run:
          name: Check formats
          command: |
            pipenv run flake8 mypkg tests
            pipenv run isort --recursive --check-only mypkg tests
      - run:
          name: Run unit tests
          command: |
            pipenv run pytest
