version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-buster
        user: circleci
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install pipenv
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - run:
          name: Create `.env`
          command: |
            echo "WORKON_HOME=/home/circleci/.pipenv/python-project-template\nPIPENV_CACHE_DIR=/home/circleci/.pipenv-cache\n" > .env
      - restore_cache:
          keys:
            - python-project-template-{{ checksum "Pipfile.lock" }}
      - run:
          name: Create an environment
          command: pipenv install
      - save_cache:
          key: python-project-template-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/.pipenv/python-project-template
            - /home/circleci/.pipenv-cache
      - run:
          name: Check formats
          command: |
            pipenv shell
            flake8 mypkg
            flake8 tests
            isort --recursive --check-only mypkg
            isort --recursive --check-only tests
      - run:
          name: Run unit tests
          command: |
            pipenv shell
            pytest
