version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-buster
        user: circleci
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install pipenv
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - run:
          name: Export environment variables
          command: echo -e 'PIPENV_VENV_IN_PROJECT=1\nPIPENV_CACHE_DIR="/home/circleci/.pipenv-cache"' > .env
      - restore_cache:
          keys:
            - python-project-template-{{ checksum "Pipfile.lock" }}
      - run:
          name: Create an environment
          command: pipenv install
      - save_cache:
          key: python-project-template-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/project/.venv
            - /home/circleci/.pipenv-cache
      - run:
          name: Check formats
          command: |
            pipenv run flake8 mypkg tests
            pipenv run isort --recursive --check-only mypkg tests
      - run:
          name: Run unit tests
          command: |
            pipenv run pytest
